# Follow guide at https://realpython.com/blog/python/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/

version: '3'

services:

  flask:
    build: .
    volumes:
     - .:/app
    environment:
      CELERY_BROKER_URL: amqp://broker
      CELERY_RESULT_BACKEND: redis://result_backend
    restart: always
    command: pipenv run gunicorn -b 0.0.0.0:5000 wsgi:app --log-level=INFO
    ports:
      - "5000:5000"
    depends_on:
     - broker
     - result_backend
     - worker

  worker:
    build: .
    volumes:
     - .:/app
    environment:
      CELERY_BROKER_URL: amqp://broker
      CELERY_RESULT_BACKEND: redis://result_backend
    restart: always
    command: pipenv run celery worker -A wsgi.celery -l INFO
    depends_on:
     - broker
     - result_backend

  broker:
    image: rabbitmq:3.7.7-alpine

  result_backend:
    image: redis:4.0.11-alpine
